name: DF-2022.1.1
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - r-base=4.1.3
  - cutadapt=4.0
  - fastqc
  - r-tidyverse=1.3.1
  - bioconductor-dada2=1.22.0
  - bioconductor-phyloseq=1.38.0
  - r-cowplot=1.1.1
  - r-kableextra=1.3.4
  - r-languageserver
  - r-httpgd
  - bioconductor-decipher
  - r-phangorn
  - r-optparse
  - dos2unix
